version: "3.2"

services:
  seafile:
    image: seafile:latest
    ports:
      - "6008:8000"
      - "6009:8082"
    environment:
      - SEAFILE_EXTERNAL_PORT=443
      - SEAFILE_HOSTNAME=seafile.yurtagames.com
      - SEAFILE_SERVER_NAME=myseafile
      - SEAFILE_ADMIN_MAIL=admin@seafile.com
      - SEAFILE_ADMIN_PASSWORD=test123
      - USE_SSL=on
    volumes:
      - ./seafile:/data
      - ./ssl:/etc/ssl
    labels:
      - traefik.seafile1.frontend.rule=Host:seafile.yurtagames.com;PathPrefixStrip:/seafhttp
      - traefik.seafile1.port=8082
      - traefik.seafile2.frontend.rule=Host:seafile.yurtagames.com
      - traefik.seafile2.port=8000
      - traefik.docker.network=traefik-proxy
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true

